version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: review_postgres
    restart: always
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: bakr_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/review_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - postgres
